-- report: customer_purchase_frequency_segments
WITH frequency AS (SELECT c.customer_id, c.customer_name, COUNT(o.order_id) AS order_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.customer_id GROUP BY c.customer_id, c.customer_name) SELECT customer_id, customer_name, order_count, CASE WHEN order_count <= 1 THEN 'One-Time' WHEN order_count <= 4 THEN 'Occasional' ELSE 'Loyal' END AS frequency_segment FROM frequency ORDER BY order_count DESC, customer_id;

-- report: customer_total_spend_segments
WITH spend AS (SELECT c.customer_id, c.customer_name, COALESCE(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 0) AS total_spend FROM customers c LEFT JOIN orders o ON o.customer_id = c.customer_id LEFT JOIN order_items i ON i.order_id = o.order_id GROUP BY c.customer_id, c.customer_name) SELECT customer_id, customer_name, ROUND(total_spend, 2) AS total_spend, CASE WHEN total_spend < 10000 THEN 'Low' WHEN total_spend < 50000 THEN 'Medium' ELSE 'High' END AS spend_segment FROM spend ORDER BY total_spend DESC;

-- report: rfm_customer_analysis
WITH reference_date AS (SELECT MAX(date(order_date)) AS max_order_date FROM orders), rfm AS (SELECT c.customer_id, c.customer_name, CAST(julianday((SELECT max_order_date FROM reference_date)) - julianday(MAX(date(o.order_date))) AS INTEGER) AS recency_days, COUNT(DISTINCT o.order_id) AS frequency, COALESCE(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 0) AS monetary FROM customers c LEFT JOIN orders o ON o.customer_id = c.customer_id LEFT JOIN order_items i ON i.order_id = o.order_id GROUP BY c.customer_id, c.customer_name), scored AS (SELECT *, 5 - NTILE(5) OVER (ORDER BY COALESCE(recency_days, 99999) ASC) AS r_score, NTILE(5) OVER (ORDER BY frequency) AS f_score, NTILE(5) OVER (ORDER BY monetary) AS m_score FROM rfm) SELECT customer_id, customer_name, recency_days, frequency, ROUND(monetary, 2) AS monetary, r_score, f_score, m_score, r_score + f_score + m_score AS rfm_score FROM scored ORDER BY rfm_score DESC, monetary DESC;

-- report: final_customer_segmentation
WITH reference_date AS (SELECT MAX(date(order_date)) AS max_order_date FROM orders), base AS (SELECT c.customer_id, c.customer_name, c.customer_type, CAST(julianday((SELECT max_order_date FROM reference_date)) - julianday(MAX(date(o.order_date))) AS INTEGER) AS recency_days, COUNT(DISTINCT o.order_id) AS frequency, COALESCE(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 0) AS monetary FROM customers c LEFT JOIN orders o ON o.customer_id = c.customer_id LEFT JOIN order_items i ON i.order_id = o.order_id GROUP BY c.customer_id, c.customer_name, c.customer_type), scored AS (SELECT *, 5 - NTILE(5) OVER (ORDER BY COALESCE(recency_days, 99999) ASC) AS r_score, NTILE(5) OVER (ORDER BY frequency) AS f_score, NTILE(5) OVER (ORDER BY monetary) AS m_score FROM base) SELECT customer_id, customer_name, customer_type, recency_days, frequency, ROUND(monetary, 2) AS monetary, CASE WHEN frequency >= 5 AND monetary >= 50000 THEN 'Champion' WHEN r_score >= 4 AND f_score >= 3 THEN 'Loyal' WHEN r_score <= 2 THEN 'At Risk' ELSE 'Developing' END AS final_segment, r_score + f_score + m_score AS rfm_score FROM scored ORDER BY rfm_score DESC, monetary DESC;

-- report: advanced_business_insights
WITH customer_orders AS (SELECT customer_id, COUNT(*) AS order_count FROM orders WHERE customer_id IS NOT NULL GROUP BY customer_id), gaps AS (SELECT julianday(date(order_date)) - julianday(LAG(date(order_date)) OVER (PARTITION BY customer_id ORDER BY date(order_date), order_id)) AS days_gap FROM orders WHERE customer_id IS NOT NULL), category_revenue AS (SELECT p.category, SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)) AS revenue FROM products p JOIN order_items i ON i.product_id = p.product_id GROUP BY p.category), category_growth AS (SELECT p.category, strftime('%Y-%m', o.order_date) AS sales_month, SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)) AS revenue FROM products p JOIN order_items i ON i.product_id = p.product_id JOIN orders o ON o.order_id = i.order_id GROUP BY p.category, sales_month), growth AS (SELECT category, sales_month, 100.0 * (revenue - LAG(revenue) OVER (PARTITION BY category ORDER BY sales_month)) / NULLIF(LAG(revenue) OVER (PARTITION BY category ORDER BY sales_month), 0) AS growth_percent FROM category_growth), region_revenue AS (SELECT o.region_code, SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)) AS revenue FROM orders o JOIN order_items i ON i.order_id = o.order_id GROUP BY o.region_code) SELECT ROUND(100.0 * SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS repeat_customer_percent, ROUND(100.0 * SUM(CASE WHEN order_count = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS one_time_customer_percent, ROUND((SELECT AVG(days_gap) FROM gaps WHERE days_gap IS NOT NULL), 2) AS average_days_between_purchases, (SELECT category FROM category_revenue ORDER BY revenue DESC LIMIT 1) AS most_valuable_category, (SELECT category FROM growth WHERE growth_percent IS NOT NULL ORDER BY growth_percent DESC LIMIT 1) AS fastest_growing_category, (SELECT region_code FROM region_revenue ORDER BY revenue DESC LIMIT 1) AS highest_revenue_region FROM customer_orders;

-- report: advanced_top_twenty_customers
SELECT c.customer_id, c.customer_name, ROUND(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 2) AS revenue FROM customers c JOIN orders o ON o.customer_id = c.customer_id JOIN order_items i ON i.order_id = o.order_id GROUP BY c.customer_id, c.customer_name ORDER BY revenue DESC LIMIT 20;

-- report: advanced_top_twenty_products
SELECT p.product_id, p.product_name, SUM(i.quantity) AS units_sold, ROUND(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 2) AS revenue FROM products p JOIN order_items i ON i.product_id = p.product_id GROUP BY p.product_id, p.product_name ORDER BY revenue DESC LIMIT 20;
